/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopassignment;
import oopassignment.Assignment;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.*;
/**
 *
 * @author User
 */
public class FacultyAdmin_FrameAssignment extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FacultyAdmin_FrameAssignment.class.getName());
    
    String FacultyAdminID = "";
    
    //Create TableObjects for Student-Supervisor Assignment Table, and declare their Column names
    private final DefaultTableModel modelAssignment = new DefaultTableModel();
    private final String[] columnNameAssignment = {"AssignID","SupervisorID","Name","StudentID","Name","StudentIntake","Course","AssignStatus"};

    private final DefaultTableModel modelSupervisor = new DefaultTableModel();
    private final String[] columnNameSupervisor = {"SupervisorID","Name","Department/Course","Num of Students","Office Location","Status"};
    
    private final DefaultTableModel modelStudent = new DefaultTableModel();
    private final String[] columnNameStudent = {"TP Number","Name","StudentIntake","Course","Status"};
    

    //Create ArrayList of assignments,students,supervisors' data
    private ArrayList<Assignment> assignmentList = new ArrayList<>();
    private ArrayList<Student> studentList = new ArrayList<>();
    private ArrayList<Supervisor> supervisorList = new ArrayList<>();
    
    //Declare Objects for filtering tables
    FA_TableFilter assignmentFilter;
    FA_TableFilter supervisorFilter;
    FA_TableFilter studentFilter;
    
    String assignIDBeforeEdit = "";
    int row = -1;
    
    //GUI Constructor
    public FacultyAdmin_FrameAssignment() {

        initComponents();

        //Set Assignment table's Column name with array
        modelAssignment.setColumnIdentifiers(columnNameAssignment);
        modelSupervisor.setColumnIdentifiers(columnNameSupervisor);
        modelStudent.setColumnIdentifiers(columnNameStudent);
        
        //Makes the table header unable to reorder
        jTableAssignment.getTableHeader().setReorderingAllowed(false);
        //Auto-resize columns to fit text (mostly)
        jTableAssignment.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        //Makes the table non-editable (Object.class means for all data types in columns, Null means cannot be edited)
        jTableAssignment.setDefaultEditor(Object.class, null);
        
        jTableSupervisor.getTableHeader().setReorderingAllowed(false);
        jTableSupervisor.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableSupervisor.setDefaultEditor(Object.class, null);
        
        jTableStudent.getTableHeader().setReorderingAllowed(false);
        jTableStudent.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableSupervisor.setDefaultEditor(Object.class, null);
        
        FA_TableManager.createObjectValues(supervisorList, studentList, assignmentList);
        
        //Display Tables with Objects
        FA_TableManager.displayAssignmentTable(modelAssignment,assignmentList);
        FA_TableManager.displaySupervisorTable(modelSupervisor,supervisorList);
        FA_TableManager.displayStudentTable(modelStudent,studentList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPreviousFrame = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSupervisorID = new javax.swing.JTextField();
        jTextFieldStudentID = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jButtonAssign = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldAssignmentID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldCourse = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSupervisor = new javax.swing.JTable();
        jTextFieldSupervisorFilterCourse = new javax.swing.JTextField();
        jButtonSupervisorFilterSearch = new javax.swing.JButton();
        jLabelFilterCourse3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();
        jTextFieldStudentFilterCourse = new javax.swing.JTextField();
        jLabelFilterCourse2 = new javax.swing.JLabel();
        jButtonStudentFilterSearch = new javax.swing.JButton();
        jTextFieldStudentFilterIntake = new javax.swing.JTextField();
        jLabelFilterIntake = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAssignment = new javax.swing.JTable();
        jTextFieldAssignmentFilterIntake = new javax.swing.JTextField();
        jLabelFilterIntake1 = new javax.swing.JLabel();
        jLabelFilterCourse4 = new javax.swing.JLabel();
        jTextFieldAssignmentFilterCourse = new javax.swing.JTextField();
        jButtonAssignmentFilterSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPreviousFrame.setText("Previous");
        jButtonPreviousFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousFrameActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("Student-Supervisor Assignment");

        jLabel2.setText("Supervisor ID");

        jLabel1.setText("Student ID");

        jButtonEdit.setText("Edit / Reassign");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonAssign.setText("Assign");
        jButtonAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAssignActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabel11.setText("Assignment ID");

        jLabel12.setText("Course");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("Assign Assignment Values");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(680, 680, 680)
                .addComponent(jLabel4))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAssign, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSupervisorID, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAssignmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAssignmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSupervisorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(21, 21, 21)
                .addComponent(jButtonAssign)
                .addGap(18, 18, 18)
                .addComponent(jButtonEdit)
                .addGap(18, 18, 18)
                .addComponent(jButtonDelete)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("View Student & Supervisor Tables");

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTableSupervisor.setModel(modelSupervisor);
        jScrollPane3.setViewportView(jTableSupervisor);

        jScrollPane1.setViewportView(jScrollPane3);

        jButtonSupervisorFilterSearch.setText("Search");
        jButtonSupervisorFilterSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupervisorFilterSearchActionPerformed(evt);
            }
        });

        jLabelFilterCourse3.setText("Course");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelFilterCourse3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldSupervisorFilterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSupervisorFilterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSupervisorFilterSearch)
                    .addComponent(jTextFieldSupervisorFilterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFilterCourse3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Supervisor", jPanel2);

        jTableStudent.setModel(modelStudent);
        jScrollPane4.setViewportView(jTableStudent);

        jScrollPane5.setViewportView(jScrollPane4);

        jLabelFilterCourse2.setText("Course");

        jButtonStudentFilterSearch.setText("Search");
        jButtonStudentFilterSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStudentFilterSearchActionPerformed(evt);
            }
        });

        jLabelFilterIntake.setText("Intake");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 367, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabelFilterCourse2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldStudentFilterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabelFilterIntake)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldStudentFilterIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonStudentFilterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStudentFilterIntake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFilterIntake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStudentFilterSearch)
                    .addComponent(jTextFieldStudentFilterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFilterCourse2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Student", jPanel5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Student-Supervisor Assignment Table");

        jTableAssignment.setModel(modelAssignment);
        jTableAssignment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableAssignmentMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTableAssignment);

        jLabelFilterIntake1.setText("Intake");

        jLabelFilterCourse4.setText("Course");

        jButtonAssignmentFilterSearch.setText("Search");
        jButtonAssignmentFilterSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAssignmentFilterSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelFilterIntake1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAssignmentFilterIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelFilterCourse4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAssignmentFilterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAssignmentFilterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAssignmentFilterSearch)
                    .addComponent(jTextFieldAssignmentFilterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFilterCourse4)
                    .addComponent(jTextFieldAssignmentFilterIntake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFilterIntake1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jScrollPane6.setViewportView(jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1957, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPreviousFrame)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButtonPreviousFrame)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAssignActionPerformed
        String assignID = jTextFieldAssignmentID.getText().trim();
        String supervisorID = jTextFieldSupervisorID.getText().trim();
        String studentID = jTextFieldStudentID.getText().trim();
        String course = jTextFieldCourse.getText().trim();
        
        //Validation object created for validating User Inputs
        FA_AssignmentValidation validation1 = new FA_AssignmentValidation(assignID,studentID,supervisorID,course,studentList,supervisorList,assignmentList);
        StringBuilder errorMessage = new StringBuilder("❌ Invalid Input! Following Issues...\n");
        validation1.setEditFlag(false);
        
        boolean validInput = true;
        if (validation1.ensureNoEmptyInput()==false){
            errorMessage.append("There are empty input Fields.\n");
            validInput = false;
        }
        if (validation1.ensureInputExists()==false){
            errorMessage.append("Entered StudentID/SupervisorID doesn't exists, course doesn't belong to student or Not in correct Format.\n");
            validInput = false;
        }
        if (validation1.ensureStudentSupervisorSameDepartment()==false){
            errorMessage.append("Entered StudentID & SupervisorID are not under the same Department/Course.\n");
            validInput = false;
        }
        if (validation1.ensureStudentSupervisorActive()==false){
            errorMessage.append("Entered StudentID/SupervisorID is not Active.\n");
            validInput = false;
        }
        if (validation1.ensureNoDuplicatedStudent()==false){
            errorMessage.append("Entered StudentID is already Assigned.\n");
            validInput = false;
        }
        if (validation1.ensureNoDuplicatedAssignID()==false){
            errorMessage.append("Entered AssignID already exists.\n");
            validInput = false;
        }
        if (validation1.ensureCorrectAssignIDFormat()==false){
            errorMessage.append("Entered AssigniD must be in \"A123\" format.\n");
            validInput = false;
        }
        
        //When User Inputs are Valid
        if (validInput == true){
            //Set Course to correct capitalization
            course = validation1.getStudentCourse();
            //Assign Derived Values to Assignment Table
            validation1.setAssignmentStatus("Active");
            validation1.deriveSupervisorStudentInfo();
            String supervisorName = validation1.getSupervisorName();
            String studentName = validation1.getStudentName();
            String studentIntake = validation1.getStudentIntake();
            String assignmentStatus = validation1.getAssignmentStatus();
            
            //Add new Assignment Object
            assignmentList.add(new Assignment(assignID,supervisorID,supervisorName,studentID,studentName,studentIntake,course,assignmentStatus));
            //Add new Row to Assignment table
            modelAssignment.addRow(assignmentList.get(assignmentList.size()-1).getAssignmentDataList());
            
            //Append new dataLine in assignment.txt
            ArrayList<String[]> newDataLine = new ArrayList<>();
            newDataLine.add(assignmentList.get(assignmentList.size()-1).getAssignmentDataList());
            FA_FileHandling.writeFile("assignment.txt", newDataLine, true);
            
            //Update Supervisor's number of students
            for (Supervisor supervisor : supervisorList){
                if (supervisor.getsupervisorID().equals(supervisorID)){
                    supervisor.countSupervisorNumberOfStudent(assignmentList);
                }
            }
            FA_FileHandling.writeSupervisorFile("supervisor.txt",supervisorList);
            FA_TableManager.displaySupervisorTable(modelSupervisor, supervisorList);
            
            // Set text fields to empty after adding valid data
            jTextFieldAssignmentID.setText("");
            jTextFieldSupervisorID.setText("");
            jTextFieldStudentID.setText("");
            jTextFieldCourse.setText("");
            
        }
        else{
            //Show error message if Invalid Input
            JOptionPane.showMessageDialog(this,errorMessage);
        }
        
        
        
        
        
        
        //Check AssignID already exist
        //Check SupervisorID exist
        //Check StudentID exist
        //Check if Intake & Course match with StudentID
        
    }//GEN-LAST:event_jButtonAssignActionPerformed

    private void jButtonSupervisorFilterSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupervisorFilterSearchActionPerformed
        //Display Original Table first to clear existing Filters
        FA_TableManager.displaySupervisorTable(modelSupervisor,supervisorList);
        //Create new table filter object
        supervisorFilter = new FA_TableFilter(modelSupervisor);
        String course = jTextFieldSupervisorFilterCourse.getText();
        
        //If Empty, clear table filter
        if (course.isEmpty()){
            FA_TableManager.displaySupervisorTable(modelSupervisor,supervisorList);
        }
        else{
            String[] filterValues = {course};
            int[] filterColumns = {2};
            supervisorFilter.applyFilters(filterValues,filterColumns);
        }
    }//GEN-LAST:event_jButtonSupervisorFilterSearchActionPerformed

    private void jButtonStudentFilterSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStudentFilterSearchActionPerformed
        FA_TableManager.displayStudentTable(modelStudent,studentList);
        studentFilter = new FA_TableFilter(modelStudent);
        String intake = jTextFieldStudentFilterIntake.getText();
        String course = jTextFieldStudentFilterCourse.getText();
        
        if (intake.isEmpty() && course.isEmpty()){
            FA_TableManager.displayStudentTable(modelStudent,studentList);
        }
        else{
            String[] filterValues = {intake,course};
            int[] filterColumn = {2,3};
            studentFilter.applyFilters(filterValues,filterColumn);
        }
    }//GEN-LAST:event_jButtonStudentFilterSearchActionPerformed

    private void jButtonAssignmentFilterSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAssignmentFilterSearchActionPerformed
        FA_TableManager.displayAssignmentTable(modelAssignment, assignmentList);
        assignmentFilter = new FA_TableFilter(modelAssignment);
        String intake = jTextFieldAssignmentFilterIntake.getText();
        String course = jTextFieldAssignmentFilterCourse.getText();
        
        if (intake.isEmpty() && course.isEmpty()){
            FA_TableManager.displayAssignmentTable(modelAssignment,assignmentList);
        }
        else{
            String[] filterValues = {intake,course};
            int[] filterColumn = {5,6};
            assignmentFilter.applyFilters(filterValues,filterColumn);
        }
    }//GEN-LAST:event_jButtonAssignmentFilterSearchActionPerformed

    private void jTableAssignmentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAssignmentMouseReleased
        //Retrieve tempRow number for Edit or Delete assignment data
        row = jTableAssignment.getSelectedRow();
        
        String assignID = String.valueOf(modelAssignment.getValueAt(row,0));
        String supervisorID = String.valueOf(modelAssignment.getValueAt(row,1));
        String tpNum = String.valueOf(modelAssignment.getValueAt(row,3));
        String course = String.valueOf(modelAssignment.getValueAt(row,6));
        
        assignIDBeforeEdit = assignID;
        
        jTextFieldAssignmentID.setText(assignID);
        jTextFieldSupervisorID.setText(supervisorID);
        jTextFieldStudentID.setText(tpNum);
        jTextFieldCourse.setText(course);
    }//GEN-LAST:event_jTableAssignmentMouseReleased

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        String assignID = jTextFieldAssignmentID.getText().trim();
        String supervisorID = jTextFieldSupervisorID.getText().trim();
        String tpNum = jTextFieldStudentID.getText().trim();
        String course = jTextFieldCourse.getText().trim();
        
        FA_AssignmentValidation validationEdit = new FA_AssignmentValidation(assignID,tpNum,supervisorID,course,studentList,supervisorList,assignmentList);
        StringBuilder errorMessage = new StringBuilder("❌ Invalid Input! Following Issues...\n");
        validationEdit.setEditFlag(true);
        validationEdit.setAssignIDBeforeEdit(assignIDBeforeEdit);
        
        boolean validInput = true;
        if (validationEdit.ensureNoEmptyInput()==false){
            errorMessage.append("There are empty input Fields.\n");
            validInput = false;
        }
        if (validationEdit.ensureInputExists()==false){
            errorMessage.append("Entered StudentID/SupervisorID doesn't exists, course doesn't belong to student or Not in correct Format.\n");
            validInput = false;
        }
        if (validationEdit.ensureStudentSupervisorSameDepartment()==false){
            errorMessage.append("Entered StudentID & SupervisorID are not under the same Department/Course.\n");
            validInput = false;
        }
        if (validationEdit.ensureStudentSupervisorActive()==false){
            errorMessage.append("Entered StudentID/SupervisorID is not Active.\n");
            validInput = false;
        }
        if (validationEdit.ensureNoDuplicatedStudent()==false){
            errorMessage.append("Entered StudentID is already Assigned.\n");
            validInput = false;
        }
        if (validationEdit.ensureNoDuplicatedAssignID()==false){
            errorMessage.append("Entered AssignID already exists.\n");
            validInput = false;
        }
        if (validationEdit.ensureCorrectAssignIDFormat()==false){
            errorMessage.append("Entered AssigniD must be in \"A123\" format.\n");
            validInput = false;
        }
        
        if (validInput == true){
            int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to Edit or Reassign?");
            if (choice==0){
                //Set Course to correct capitalization
                course = validationEdit.getStudentCourse();
                //Assign Values to Assignment Table
                validationEdit.setAssignmentStatus("Active");
                validationEdit.deriveSupervisorStudentInfo();
                String supervisorName = validationEdit.getSupervisorName();
                String studentName = validationEdit.getStudentName();
                String studentIntake = validationEdit.getStudentIntake();
                String assignmentStatus = validationEdit.getAssignmentStatus();

                //Replace original data with new data
                for (Assignment data : assignmentList){
                    if (data.getAssignID().equals(assignIDBeforeEdit)){
                        data.setAssignID(assignID);
                        data.setSupervisorID(supervisorID);
                        data.setSupervisorName(supervisorName);
                        data.setTpNum(tpNum);
                        data.setStudentName(studentName);
                        data.setIntakeCode(studentIntake);
                        data.setCourse(course);
                        data.setAssignStatus(assignmentStatus);
                    }
                }

                //Find which Row is Selected, then modify row data
                //Used tempRow instead of row (because row value may not belong to the actual selected row after filtering table)
                for (int tempRow = 0; tempRow < modelAssignment.getRowCount(); tempRow++) {
                    String currentAssignID = modelAssignment.getValueAt(tempRow, 0).toString(); // Assume ID is in column 0
                    if (currentAssignID.equals(assignIDBeforeEdit)) {
                        // Found the matching tempRow, now update other columns
                        modelAssignment.setValueAt(assignID, tempRow, 0);
                        modelAssignment.setValueAt(supervisorID, tempRow, 1);
                        modelAssignment.setValueAt(supervisorName, tempRow, 2);
                        modelAssignment.setValueAt(tpNum, tempRow, 3);
                        modelAssignment.setValueAt(studentName, tempRow, 4);
                        modelAssignment.setValueAt(studentIntake, tempRow, 5);
                        modelAssignment.setValueAt(course, tempRow, 6);
                        modelAssignment.setValueAt(assignmentStatus, tempRow, 7);
                        break; 
                    }
                }



                //append new data tempRow to assignment.txt
                FA_FileHandling.writeAssignmentFile("assignment.txt", assignmentList);

                //Counnting and Updating Number of Students for each Supervisor
                for (Supervisor supervisor : supervisorList){
                    if (supervisor.getsupervisorID().equals(supervisorID)){
                        supervisor.countSupervisorNumberOfStudent(assignmentList);
                    }
                }
                FA_FileHandling.writeSupervisorFile("supervisor.txt",supervisorList);

                FA_TableManager.displaySupervisorTable(modelSupervisor, supervisorList);



                // Set text fields to empty after adding valid data
                jTextFieldAssignmentID.setText("");
                jTextFieldSupervisorID.setText("");
                jTextFieldStudentID.setText("");
                jTextFieldCourse.setText("");
            }
        }
        else{
            JOptionPane.showMessageDialog(this,errorMessage);
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        
        String assignID = jTextFieldAssignmentID.getText().trim();
        String supervisorID = jTextFieldSupervisorID.getText().trim();
        String tpNum = jTextFieldStudentID.getText().trim();
        String course = jTextFieldCourse.getText().trim();
        
        int choice = JOptionPane.showConfirmDialog(this,"Are you sure you want to Delete selected Data:\n  "+assignID+", "+supervisorID+", "+tpNum+", "+course);
        if (choice == 0){
            for (Assignment data : assignmentList){
                if (data.getAssignID().equals(assignID)){
                    assignmentList.remove(data);     
                    break;
                }
            }
            FA_FileHandling.writeAssignmentFile("assignment.txt", assignmentList);
                    
            for(Supervisor supervisor : supervisorList){
                if (supervisor.getsupervisorID().equals(supervisorID)){
                    supervisor.countSupervisorNumberOfStudent(assignmentList);
                    break;
                }
            }
            FA_FileHandling.writeSupervisorFile("supervisor.txt",supervisorList);

            //Update new Table values after deleting tempRow
            for (int tempRow = 0; tempRow < modelAssignment.getRowCount(); tempRow++) {
                String currentAssignID = modelAssignment.getValueAt(tempRow, 0).toString(); // Assume ID is in column 0
                if (currentAssignID.equals(assignIDBeforeEdit)) {
                    modelAssignment.removeRow(tempRow);
                }
            }
            
            FA_TableManager.displaySupervisorTable(modelSupervisor,supervisorList);

            jTextFieldAssignmentID.setText("");
            jTextFieldSupervisorID.setText("");
            jTextFieldStudentID.setText("");
            jTextFieldCourse.setText("");
        }
        
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed


    
    private void jButtonPreviousFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousFrameActionPerformed
        FacultyAdmin_FrameHome FA_FrameHome = new FacultyAdmin_FrameHome();
        FA_FrameHome.setFacultyAdminID(FacultyAdminID);
        FA_FrameHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPreviousFrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FacultyAdmin_FrameAssignment().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAssign;
    private javax.swing.JButton jButtonAssignmentFilterSearch;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonPreviousFrame;
    private javax.swing.JButton jButtonStudentFilterSearch;
    private javax.swing.JButton jButtonSupervisorFilterSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFilterCourse2;
    private javax.swing.JLabel jLabelFilterCourse3;
    private javax.swing.JLabel jLabelFilterCourse4;
    private javax.swing.JLabel jLabelFilterIntake;
    private javax.swing.JLabel jLabelFilterIntake1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableAssignment;
    private javax.swing.JTable jTableStudent;
    private javax.swing.JTable jTableSupervisor;
    private javax.swing.JTextField jTextFieldAssignmentFilterCourse;
    private javax.swing.JTextField jTextFieldAssignmentFilterIntake;
    private javax.swing.JTextField jTextFieldAssignmentID;
    private javax.swing.JTextField jTextFieldCourse;
    private javax.swing.JTextField jTextFieldStudentFilterCourse;
    private javax.swing.JTextField jTextFieldStudentFilterIntake;
    private javax.swing.JTextField jTextFieldStudentID;
    private javax.swing.JTextField jTextFieldSupervisorFilterCourse;
    private javax.swing.JTextField jTextFieldSupervisorID;
    // End of variables declaration//GEN-END:variables

    public void setFacultyAdminID(String FacultyAdminID){
        this.FacultyAdminID = FacultyAdminID;
    }
}






