/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopassignment;

import oopassignment.Assignment;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FacultyAdmin_FrameReport extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FacultyAdmin_FrameReport.class.getName());
    
    String FacultyAdminID = "";
    
    //Create TableObjects for Student-Supervisor Assignment Table, and declare their Column names
    private final DefaultTableModel modelAssignment = new DefaultTableModel();
    private final String[] columnNameAssignment = {"AssignID","SupervisorID","Name","StudentID","Name","StudentIntake","Course","AssignStatus"};
    
    private final DefaultTableModel modelSupervisor = new DefaultTableModel();
    private final String[] columnNameSupervisor = {"SupervisorID","Name","Department/Course","Num of Students","Office Location","Status"};
    
    private final DefaultTableModel modelStudent = new DefaultTableModel();
    private final String[] columnNameStudent = {"TP Number","Name","StudentIntake","Course","Status"};
    
    //Create ArrayList of assignments,students,supervisors' data
    private ArrayList<Assignment> assignmentList = new ArrayList<>();
    private ArrayList<Student> studentList = new ArrayList<>();
    private ArrayList<Supervisor> supervisorList = new ArrayList<>();
    
    //Declare Objects for filtering tables
    FA_TableFilter assignmentFilter;
    FA_TableFilter supervisorFilter;
    FA_TableFilter studentFilter;
    
    //Declare Data For Report Generation
    int totalActiveStudentCount = 0;
    int assignedStudentCount = 0;
    int totalActiveSupervisorCount = 0;
    
    //in String[], index:0 = intakeCode, index:1 = numberOfStudents
    ArrayList<String[]> intakeCodeList = new ArrayList<>();
    
    //in String[], index:0 = courseName, index:1 = numberOfStudents
    ArrayList<String[]> courseList = new ArrayList<>();
    

    /**
     * Creates new form FacultyAdmin_Frame2
     */
    public FacultyAdmin_FrameReport() {
        
        initComponents();
        
        modelAssignment.setColumnIdentifiers(columnNameAssignment);
        modelSupervisor.setColumnIdentifiers(columnNameSupervisor);
        modelStudent.setColumnIdentifiers(columnNameStudent);
        
        //Makes the table header unable to reorder
        jTableAssignment.getTableHeader().setReorderingAllowed(false);
        //Auto-resize columns to fit text
        jTableAssignment.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        //Makes the table non-editable (Object.class means for all data types in columns, Null means cannot be edited)
        jTableAssignment.setDefaultEditor(Object.class, null);
        
        jTableSupervisor.getTableHeader().setReorderingAllowed(false);
        jTableSupervisor.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        jTableStudent.getTableHeader().setReorderingAllowed(false);
        jTableStudent.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        FA_TableManager.createObjectValues(supervisorList, studentList, assignmentList);
        
        //Display Tables with Objects
        FA_TableManager.displayAssignmentTable(modelAssignment,assignmentList);
        FA_TableManager.displaySupervisorTable(modelSupervisor,supervisorList);
        FA_TableManager.displayStudentTable(modelStudent,studentList);
        
        setReportRelatedData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPreviousFrame = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxReportSelection = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonGenerateReport = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaReport = new javax.swing.JTextArea();
        jButtonClearReport = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jTextFieldAssignmentFilterIntake = new javax.swing.JTextField();
        jLabelFilterIntake4 = new javax.swing.JLabel();
        jLabelFilterCourse7 = new javax.swing.JLabel();
        jTextFieldAssignmentFilterCourse = new javax.swing.JTextField();
        jButtonAssignmentFilterSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAssignment = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableSupervisor = new javax.swing.JTable();
        jTextFieldSupervisorFilterCourse = new javax.swing.JTextField();
        jButtonSupervisorFilterSearch = new javax.swing.JButton();
        jLabelFilterCourse3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();
        jTextFieldStudentFilterCourse = new javax.swing.JTextField();
        jLabelFilterCourse2 = new javax.swing.JLabel();
        jButtonStudentFilterSearch = new javax.swing.JButton();
        jTextFieldStudentFilterIntake = new javax.swing.JTextField();
        jLabelFilterIntake = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPreviousFrame.setText("Previous");
        jButtonPreviousFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousFrameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Report Generation");

        jComboBoxReportSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Students Per Intake", "Students Per Supervisor" }));

        jLabel2.setText("Select Report Type");

        jButtonGenerateReport.setText("Generate Report");
        jButtonGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateReportActionPerformed(evt);
            }
        });

        jTextAreaReport.setColumns(20);
        jTextAreaReport.setRows(5);
        jScrollPane3.setViewportView(jTextAreaReport);

        jButtonClearReport.setText("Clear Report");
        jButtonClearReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxReportSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonClearReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGenerateReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxReportSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGenerateReport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonClearReport)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("View Assigment & Supervisor & Student Tables");

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelFilterIntake4.setText("Intake");

        jLabelFilterCourse7.setText("Course");

        jButtonAssignmentFilterSearch.setText("Search");
        jButtonAssignmentFilterSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAssignmentFilterSearchActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTableAssignment.setModel(modelAssignment);
        jScrollPane2.setViewportView(jTableAssignment);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(645, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabelFilterCourse7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAssignmentFilterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabelFilterIntake4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAssignmentFilterIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonAssignmentFilterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAssignmentFilterIntake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFilterIntake4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAssignmentFilterSearch)
                    .addComponent(jTextFieldAssignmentFilterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFilterCourse7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTabbedPane2.addTab("Assignment", jPanel8);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTableSupervisor.setModel(modelSupervisor);
        jScrollPane4.setViewportView(jTableSupervisor);

        jScrollPane1.setViewportView(jScrollPane4);

        jButtonSupervisorFilterSearch.setText("Search");
        jButtonSupervisorFilterSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupervisorFilterSearchActionPerformed(evt);
            }
        });

        jLabelFilterCourse3.setText("Course");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelFilterCourse3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldSupervisorFilterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSupervisorFilterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSupervisorFilterSearch)
                    .addComponent(jTextFieldSupervisorFilterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFilterCourse3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Supervisor", jPanel2);

        jTableStudent.setModel(modelStudent);
        jScrollPane8.setViewportView(jTableStudent);

        jScrollPane5.setViewportView(jScrollPane8);

        jLabelFilterCourse2.setText("Course");

        jButtonStudentFilterSearch.setText("Search");
        jButtonStudentFilterSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStudentFilterSearchActionPerformed(evt);
            }
        });

        jLabelFilterIntake.setText("Intake");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabelFilterCourse2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldStudentFilterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabelFilterIntake)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldStudentFilterIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonStudentFilterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStudentFilterIntake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFilterIntake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStudentFilterSearch)
                    .addComponent(jTextFieldStudentFilterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFilterCourse2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Student", jPanel7);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButtonPreviousFrame))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 646, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButtonPreviousFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(740, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSupervisorFilterSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupervisorFilterSearchActionPerformed
        //Display Original Table first to clear existing Filters
        FA_TableManager.displaySupervisorTable(modelSupervisor,supervisorList);
        //Create new table filter object
        supervisorFilter = new FA_TableFilter(modelSupervisor);
        String course = jTextFieldSupervisorFilterCourse.getText();

        //If Empty, clear table filter
        if (course.isEmpty()){
            FA_TableManager.displaySupervisorTable(modelSupervisor,supervisorList);
        }
        else{
            String[] filterValues = {course};
            int[] filterColumns = {2};
            supervisorFilter.applyFilters(filterValues,filterColumns);
        }
    }//GEN-LAST:event_jButtonSupervisorFilterSearchActionPerformed

    private void jButtonStudentFilterSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStudentFilterSearchActionPerformed
        FA_TableManager.displayStudentTable(modelStudent,studentList);
        studentFilter = new FA_TableFilter(modelStudent);
        String intake = jTextFieldStudentFilterIntake.getText();
        String course = jTextFieldStudentFilterCourse.getText();

        if (intake.isEmpty() && course.isEmpty()){
            FA_TableManager.displayStudentTable(modelStudent,studentList);
        }
        else{
            String[] filterValues = {intake,course};
            int[] filterColumn = {2,3};
            studentFilter.applyFilters(filterValues,filterColumn);
        }
    }//GEN-LAST:event_jButtonStudentFilterSearchActionPerformed

    private void jButtonAssignmentFilterSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAssignmentFilterSearchActionPerformed
        FA_TableManager.displayAssignmentTable(modelAssignment, assignmentList);
        assignmentFilter = new FA_TableFilter(modelAssignment);
        String intake = jTextFieldAssignmentFilterIntake.getText();
        String course = jTextFieldAssignmentFilterCourse.getText();

        if (intake.isEmpty() && course.isEmpty()){
            FA_TableManager.displayAssignmentTable(modelAssignment,assignmentList);
        }
        else{
            String[] filterValues = {intake,course};
            int[] filterColumn = {5,6};
            assignmentFilter.applyFilters(filterValues,filterColumn);
        }
    }//GEN-LAST:event_jButtonAssignmentFilterSearchActionPerformed

    private void jButtonGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateReportActionPerformed
        String selectedReport = jComboBoxReportSelection.getSelectedItem().toString();
        StringBuilder report = new StringBuilder();
        
        //Retrieve Date & Time of report generation
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MMM yyyy, hh.mm a");
        String generatedDateTime = now.format(formatter);
        
        report.append(String.format("""
                                    ========================================
                                     APU Supervision Report
                                    ========================================
                                    Report Type: %s
                                    Generated On: %s
                                    ========================================
                                    """,selectedReport,generatedDateTime));
        
        String reportText = "";
        if (selectedReport.equals("Students Per Intake")){
            report.append(String.format("""
                          Total Number of IntakeCodes: %s
                          Total Number of Active Students: %s
                          ========================================
                          --------------------------------------------------------------------
                          """,Integer.toString(intakeCodeList.size()),totalActiveStudentCount));
            
            reportText = generateReportStudentPerIntake(report).toString();
            
        }
        else if (selectedReport.equals("Students Per Supervisor")){
            report.append(String.format("""
                                        Total Number of Active Supervisor: %d
                                        Total Number of Active Students: %d
                                        
                                        Number of Assigned Students: %d
                                        Number of Unassigned Students: %d
                                        """,totalActiveSupervisorCount,totalActiveStudentCount,assignedStudentCount,(totalActiveStudentCount-assignedStudentCount)));
            
            reportText = generateReportStudentPerSupervisor(report).toString();
        }
        
        jTextAreaReport.setText(reportText);
        
    }//GEN-LAST:event_jButtonGenerateReportActionPerformed

    private void jButtonClearReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearReportActionPerformed

        jTextAreaReport.setText("");
    }//GEN-LAST:event_jButtonClearReportActionPerformed

    private void jButtonPreviousFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousFrameActionPerformed
        FacultyAdmin_FrameHome FA_FrameHome = new FacultyAdmin_FrameHome();
        FA_FrameHome.setFacultyAdminID(FacultyAdminID);
        FA_FrameHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPreviousFrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FacultyAdmin_FrameReport().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAssignmentFilterSearch;
    private javax.swing.JButton jButtonClearReport;
    private javax.swing.JButton jButtonGenerateReport;
    private javax.swing.JButton jButtonPreviousFrame;
    private javax.swing.JButton jButtonStudentFilterSearch;
    private javax.swing.JButton jButtonSupervisorFilterSearch;
    private javax.swing.JComboBox<String> jComboBoxReportSelection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFilterCourse2;
    private javax.swing.JLabel jLabelFilterCourse3;
    private javax.swing.JLabel jLabelFilterCourse7;
    private javax.swing.JLabel jLabelFilterIntake;
    private javax.swing.JLabel jLabelFilterIntake4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableAssignment;
    private javax.swing.JTable jTableStudent;
    private javax.swing.JTable jTableSupervisor;
    private javax.swing.JTextArea jTextAreaReport;
    private javax.swing.JTextField jTextFieldAssignmentFilterCourse;
    private javax.swing.JTextField jTextFieldAssignmentFilterIntake;
    private javax.swing.JTextField jTextFieldStudentFilterCourse;
    private javax.swing.JTextField jTextFieldStudentFilterIntake;
    private javax.swing.JTextField jTextFieldSupervisorFilterCourse;
    // End of variables declaration//GEN-END:variables
    
    public final void setReportRelatedData(){
        
        for (Student student : studentList){
            
            //Skip student if they are Inactive
            if(student.getStatus().equals("Inactive")){
                continue;
            }
            String tpNum = student.gettpNum();
            String studentIntake = student.getintakecode();
            String studentCourse = student.getCourse();
            //Check if Intake List contains intakeCode of student
            boolean intakeAdded = false;
            for(String[] intake : intakeCodeList){
                if (intake[0].equals(studentIntake)){
                    intakeAdded = true;
                    break;
                }
            }
            //Add intakeCode to List if not yet added
            if (intakeAdded == false){
                intakeCodeList.add(new String[]{studentIntake,"0"});
            }
            
            //Add up numberOfStudents for each intake
            for (String[] intake : intakeCodeList){
                if(intake[0].equals(studentIntake)){
                    int numOfStudents = Integer.parseInt(intake[1]);
                    numOfStudents++;
                    intake[1] = Integer.toString(numOfStudents);
                }
            }
            //Check if course is added in list
            boolean courseAdded = false;
            for (String[] course : courseList){
                if (course[0].equals(studentCourse)){
                    courseAdded = true;
                    break;
                }
            }
            //Add course to list if not yet added
            if (courseAdded == false){
                courseList.add(new String[]{studentCourse,"0"});
            }
            
            //Add up numberOfStudents for each Course
            for (String[] course : courseList){
                
                if(course[0].equals(studentCourse)){
                    int numOfStudents = Integer.parseInt(course[1]);
                    numOfStudents++;
                    course[1] = Integer.toString(numOfStudents);
                }
            }
            
            totalActiveStudentCount++;
        }
        
        for (Supervisor supervisor : supervisorList){
            assignedStudentCount += Integer.parseInt(supervisor.getnumberofStudent());
            String supervisorDepartment = supervisor.getDepartment();
            
            //Check if additional course is added in list
            boolean courseAdded = false;
            for (String[] course : courseList){
                if (course[0].equals(supervisorDepartment)){
                    courseAdded = true;
                    break;
                }
            }
            //Add course to list if not yet added
            if (courseAdded == false){
                courseList.add(new String[]{supervisorDepartment,"0"});
            }
            totalActiveSupervisorCount++;
        }
        
        
    }
    

    public StringBuilder generateReportStudentPerIntake(StringBuilder report){
        
        for(String[] intake : intakeCodeList){
            report.append(String.format("""
                                        Intake Code: %s
                                        
                                        Total Number of Students: %s
                                        
                                        Courses:
                                        """,intake[0],intake[1]));
            for(String[] course : courseList){
                int intakecourseNumOfStudents = 0;
                for(Student student : studentList){
                    if(student.getintakecode().equals(intake[0]) && student.getCourse().equals(course[0])){
                        intakecourseNumOfStudents++;
                    }
                }
                report.append(String.format("""
                                                - %s (%d Students)
                                            """,course[0],intakecourseNumOfStudents));
            }
            report.append(String.format("""
                                        
                                        ---------------------------------------------------------------------
                                        """));
            
        }
        report.append(String.format("""
                                    ========================================
                                     End Of Report
                                    ========================================
                                    """));
        
        return report;
    }
    
    public StringBuilder generateReportStudentPerSupervisor(StringBuilder report){
        for (String[] course : courseList){
            boolean supervisorBelongstoCurrentCourse = false;
            report.append(String.format("""
                                        ========================================
                                        ----- Course: %s -----
                                        """,course[0]));
            for (Supervisor supervisor : supervisorList){
                if (!(supervisor.getDepartment().equals(course[0]))){
                    continue;
                }
                else{
                    supervisorBelongstoCurrentCourse = true;
                }
                
                
                String supervisorID = supervisor.getsupervisorID();
                String supervisorName = supervisor.getName();
                String supervisorNumOfStudents = supervisor.getnumberofStudent();
                
                report.append(String.format("""
                                            ---------------------------------------------------------------------
                                            Supervisor: %s, %s
                                            Assigned Students: %s
                                            
                                            """,supervisorID,supervisorName,supervisorNumOfStudents));
                
                //Get supervisor assigned students
                ArrayList<String[]> assignedStudents = new ArrayList<>();
                ArrayList<String> assignedIntakes = new ArrayList<>();
                
                for (Assignment data : assignmentList){
                    if (data.getSupervisorID().equals(supervisorID)){
                        assignedStudents.add(new String[]{data.getTpNum(),data.getStudentName(),data.getIntakeCode()});
                        if (!assignedIntakes.contains(data.getIntakeCode())){
                            assignedIntakes.add(data.getIntakeCode());
                        }
                    }     
                }
                
                Collections.sort(assignedIntakes);
                for (String intakeCode : assignedIntakes){
                    report.append(intakeCode+"\n");
                    
                    for (String[] data : assignedStudents){
                        if (data[2].equals(intakeCode)){
                            report.append(String.format("""
                                                        - %s, %s
                                                        """,data[0],data[1]));
                        }
                    }
                    report.append("\n");
                }
            }
            if (supervisorBelongstoCurrentCourse == false){
                    report.append("""
                                  ---------------------------------------------------------------------
                                  No Supervisor in the Course
                                  
                                  """);
            }
        }
        report.append(String.format("""
                                    ========================================
                                     End Of Report
                                    ========================================
                                    """));
        
        return report;
    }
    
    public void setFacultyAdminID(String FacultyAdminID){
        this.FacultyAdminID = FacultyAdminID;
    }


}
