/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopassignment;


import java.io.*;
import javax.swing.table.DefaultTableModel;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

public class FeedbackGUI extends javax.swing.JFrame {
    private String supervisorID;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FeedbackGUI.class.getName());


    public FeedbackGUI(String supervisorID) {
        initComponents();
        this.supervisorID = supervisorID;
        jLabel1.setText("Supervisor ID: " + supervisorID);
        setupTable();
        loadappointmentsData();
        
        jTable1.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            jTextField1.setText(jTable1.getValueAt(row, 0).toString()); 
            jTextField2.setText(jTable1.getValueAt(row, 2).toString()); 
            jTextField3.setText(jTable1.getValueAt(row, 3).toString()); 
            jTextArea1.setText(jTable1.getValueAt(row, 5).toString()); 
        }
        }
    });
        

jTextField1.setEditable(false);
jTextField2.setEditable(false);
jTextField3.setEditable(false);
        }
        
                
        
    
    private void setupTable() {
    String[] columnNames = {"tpNum","supervisorID", "Date", "Time", "Status","feedback"};
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(columnNames, 0);
    jTable1.setModel(model);
    
    jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);   // tpNum
    jTable1.getColumnModel().getColumn(1).setPreferredWidth(20);  // supervisorID
    jTable1.getColumnModel().getColumn(2).setPreferredWidth(30);  // Date
    jTable1.getColumnModel().getColumn(3).setPreferredWidth(30);   // Time
    jTable1.getColumnModel().getColumn(4).setPreferredWidth(30);   // Status
    jTable1.getColumnModel().getColumn(5).setPreferredWidth(700);
     }
    
    
    private void loadappointmentsData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 

        try (BufferedReader br = new BufferedReader(new FileReader("appointments.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length == 6) {
                    String tpNum = parts[0].trim();
                    String supID = parts[1].trim();
                    String date = parts[2].trim();
                    String time = parts[3].trim();
                    String status = parts[4].trim();
                    String feedback = parts[5].trim();

                    
                    if (this.supervisorID.equals(supID) && "Completed".equalsIgnoreCase(status)) {
                        model.addRow(new Object[]{tpNum,supID,date,time,status,feedback});
                    }
                }
            }
        } catch (IOException e) {
            System.out.println("can not read appointments.txt: " + e.getMessage());
        }
    }
 
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("SupervisorID:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel2.setText("TP number:");

        jLabel3.setText("Date:");

        jLabel4.setText("Time:");

        jLabel5.setText("Feedback:");

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(16, 16, 16)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//      Mainpage sp = new Mainpage();
//      sp.setVisible(true);
//      this.dispose();
      
      new Mainpage(supervisorID).setVisible(true);
      this.dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    int row = jTable1.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Please select a record first!");
        return;
    }

    String tp = jTable1.getValueAt(row, 0).toString();
    String supID = jTable1.getValueAt(row, 1).toString();
    String date = jTable1.getValueAt(row, 2).toString();
    String time = jTable1.getValueAt(row, 3).toString();
    String status = jTable1.getValueAt(row, 4).toString();
    String fileFeedback = jTable1.getValueAt(row, 5).toString();

    String newFeedback = jTextArea1.getText().trim();

    if (newFeedback.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter feedback!");
        return;
    }

    if (newFeedback.contains(",")) {
        JOptionPane.showMessageDialog(this, "Feedback cannot contain commas (,). Please remove them!");
        return;
    }

    if (!fileFeedback.equals("-")) {
        JOptionPane.showMessageDialog(this, "This record already has feedback! Please use Edit instead.");
        return;
    }
    
    if (newFeedback.contains("-")) {
        JOptionPane.showMessageDialog(this, "Feedback cannot contain commas (-). Please remove them!");
        return;
    }
    
//    if (fileFeedback.equals("-")) {
//        JOptionPane.showMessageDialog(this, "Please write feedback.");
//        return;
//    }

    Feedback feedback = new Feedback(tp, supID, date, time, status, newFeedback);

    File inputFile = new File("appointments.txt");
    File tempFile = new File("temp.txt");
    boolean added = false;

    try (
        BufferedReader reader = new BufferedReader(new FileReader(inputFile));
        BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))
    ) {
        String line;
        while ((line = reader.readLine()) != null) {
            String[] parts = line.split(",");
            if (parts.length == 6) {
                String fileTP = parts[0].trim();
                String fileSupID = parts[1].trim();
                String fileDate = parts[2].trim();
                String fileTime = parts[3].trim();

                if (fileTP.equals(tp) && fileSupID.equals(supID) &&
                    fileDate.equals(date) && fileTime.equals(time)) {

                    line = feedback.toFileString();
                    added = true;
                }
            }
            writer.write(line);
            writer.newLine();
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error reading/writing file: " + e.getMessage());
        return;
    }

    if (inputFile.delete() && tempFile.renameTo(inputFile)) {
        if (added) {
            JOptionPane.showMessageDialog(this, "Feedback added successfully!");
            loadappointmentsData(); 

            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextArea1.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Record not found!");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Error replacing file!");
    }


    
   

    
       



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased

    }//GEN-LAST:event_jTable1MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int row = jTable1.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Please select a record to edit!");
        return;
    }
    

    
    String tp = jTable1.getValueAt(row, 0).toString();
    String supID = jTable1.getValueAt(row, 1).toString();
    String date = jTable1.getValueAt(row, 2).toString();
    String time = jTable1.getValueAt(row, 3).toString();
    String status = jTable1.getValueAt(row, 4).toString();
    String feedbackText = jTextArea1.getText();

    Feedback feedback = new Feedback(tp, supID, date, time, status, feedbackText);
    
    File inputFile = new File("appointments.txt");
    File tempFile = new File("temp.txt");
    boolean updated = false;
    
    if (feedbackText.equals("-")) {
        JOptionPane.showMessageDialog(this, " Please use Add button.");
        return;
    }
    
    if (feedbackText.contains(",")) {
        JOptionPane.showMessageDialog(this, "Feedback cannot contain commas (,). Please remove them!");
        return;
    }
    
    if (feedbackText.isEmpty()) {
        feedbackText = "-";
    }
    feedback.setFeedback(feedbackText);

    try (
        BufferedReader reader = new BufferedReader(new FileReader(inputFile));
        BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))
    ) {
        String line;
        while ((line = reader.readLine()) != null) {
            String[] parts = line.split(",");
            if (parts.length == 6) {
                String fileTP = parts[0].trim();
                String fileSupID = parts[1].trim();
                String fileDate = parts[2].trim();
                String fileTime = parts[3].trim();

                if (fileTP.equals(tp) && fileSupID.equals(supID) &&
                    fileDate.equals(date) && fileTime.equals(time)) {

                    line = feedback.toFileString();
                    updated = true;
                }
            }
            writer.write(line);
            writer.newLine();
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error reading or writing file: " + e.getMessage());
        return;
    }

    if (inputFile.delete() && tempFile.renameTo(inputFile)) {
        if (updated) {
            JOptionPane.showMessageDialog(this, "Feedback updated successfully!");
            loadappointmentsData(); 
            
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextArea1.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Record not found!");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Error replacing file!");
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
