package oopassignment;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class LoginPage2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginPage2.class.getName());

    /**
     * Creates new form LoginPage2
     */
    public LoginPage2() {
        initComponents();
    }
    
    private String checkStatus(String fileName, String id){
        try{
            FileReader fr = new FileReader(fileName);
            BufferedReader br = new BufferedReader(fr);
            String eachLine;

            while((eachLine = br.readLine()) != null){
                String parts[] = eachLine.split(",");
                if (parts[0].equals(id)){
                    return parts[parts.length - 1];
                }
            }
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "Error Reading " + fileName);
        }
        return null;
    }
    
    private void addAttempts(String id){
        try{
            FileReader fr = new FileReader("Accounts.txt");
            BufferedReader br = new BufferedReader(fr);
            ArrayList<String> updatedList = new ArrayList<>();
            String eachLine;
            
            while((eachLine = br.readLine()) != null){
                String parts[] = eachLine.split(",");
                if (parts[0].trim().equals(id) && parts.length > 3){
                    int attempts = 0;
                    try{
                        attempts = Integer.parseInt(parts[3].trim());
                    }catch(NumberFormatException e){
                        attempts = 0;
                    }
                    parts[3] = String.valueOf(attempts + 1);
                    eachLine = String.join(",", parts);
                }
                updatedList.add(eachLine);
            }
            
            br.close();
            fr.close();
            
            FileWriter fw = new FileWriter("Accounts.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            
            for (String line : updatedList){
                bw.write(line);
                bw.newLine();
            }
            
            bw.close();
            fw.close();
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "Error updating Accounts.txt");
        }   
    }
    
    private void resetAttempts(String id){
        try{
            FileReader fr = new FileReader("Accounts.txt");
            BufferedReader br = new BufferedReader(fr);
            
            ArrayList<String> updatedList = new ArrayList<>();
            String eachLine;
            
            while((eachLine = br.readLine()) != null){
                String parts[] = eachLine.split(",");
                if (parts[0].trim().equals(id) && parts.length > 3){
                    parts[3] = "0";
                    eachLine = String.join(",", parts);
                }
                updatedList.add(eachLine);
            }
            
            br.close();
            fr.close();
            
            FileWriter fw = new FileWriter("Accounts.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            
            for (String line : updatedList){
                bw.write(line);
                bw.newLine();
            }
            
            bw.close();
            fw.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "Error when reseting attempts in Accounts.txt: " + e.getMessage(), "File Read Writer Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Log in to APU Supervision Management System");

        jLabel2.setText("User ID:");

        jLabel3.setText("Password:");

        jButton1.setText("Log in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String userID = jTextField1.getText();
        String password = jTextField2.getText();
        
        try{
            FileReader fr = new FileReader("Accounts.txt");
            BufferedReader br = new BufferedReader(fr);
            String eachLine;
            
            boolean success = false;
            
            while((eachLine = br.readLine()) != null){
                String parts[] = eachLine.split(",");
                String accountID = parts[0].trim();
                String accountPassword = parts[1].trim();
                String role = parts[2].trim();
                
                int attempts = 0;
                
                if(!role.equalsIgnoreCase("System Admin")){
                    if(parts.length >= 4){
                        try{
                            attempts = Integer.parseInt(parts[3].trim());
                        }catch(NumberFormatException e){
                            attempts = 0;
                        }
                    }else{
                        attempts = 0;
                    }
                }
                
                
                if(userID.equals(accountID)){
                    String status = "";
                    success = true;
                    if(role.equals("Student")){
                        status = checkStatus("students.txt", accountID);
                    }else if(role.equals("Supervisor")){
                        status = checkStatus("supervisor.txt", accountID);
                    }else if(role.equals("Faculty Admin")){
                        status = checkStatus("facultyAdmin.txt", accountID);
                    }else if(role.equals("System Admin")){
                        status = checkStatus("systemAdmin.txt", accountID);
                    }  
                        
                    if((role.equalsIgnoreCase("System Admin") || attempts < 3) && (status.equalsIgnoreCase("active"))){
                        if(password.equals(accountPassword)){
                            resetAttempts(accountID);
                            
                            if(role.equals("Student")){
                                StudentMainPage smp = new StudentMainPage(userID);
                                smp.setVisible(true);
                                this.dispose();
                            }else if(role.equals("Supervisor")){
                                Mainpage m = new Mainpage(userID);
                                m.setVisible(true);
                                this.dispose();
                            }else if(role.equals("Faculty Admin")){
                                FacultyAdmin_FrameHome FA_frameHome = new FacultyAdmin_FrameHome();
                                FA_frameHome.setVisible(true);
                                FA_frameHome.setFacultyAdminID(userID);
                                this.dispose();
                            }else if(role.equals("System Admin")){
                                SystemAdminMainMenu mainMenu = new SystemAdminMainMenu();
                                mainMenu.setVisible(true);
                                this.dispose();
                            }  
                        }else{
                            addAttempts(accountID);
                            JOptionPane.showMessageDialog(this, "user ID or password is incorrect");
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "Your account is inactive or has too many attempts, please try again later");
                    }
                    break;
                }
                
            }    
            br.close();
            fr.close();
                
            if(!success){
                JOptionPane.showMessageDialog(this, "user ID or password is incorrect");
            }
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "Error reading Accounts.txt: " + e.getMessage(), "File Read Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginPage2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
