
package oopassignment;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Reschedule extends javax.swing.JFrame {
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CheckTimeSlot.class.getName());
    private static final String FILE_TS = "timeslot.txt";
    private static final String FILE_AP = "appointments.txt";
    private static final String FILE_AS = "assignment.txt";
    private final String tpNum;
    private final String supervisorID;
    private final String date;
    private final String time;
    
    
    private final DefaultTableModel model = new DefaultTableModel();
    private final String[] columnName = { "Supervisor ID", "Date", "Time", "Status" };
    private int row = -1;
    
    
    
    public Reschedule(String tpNum, String supervisorID, String date, String time) {
        this.tpNum = tpNum;
        this.supervisorID = supervisorID;
        this.date = date;
        this.time = time;
        model.setColumnIdentifiers(columnName);
        initComponents();
        jTable1.setModel(model);
        jTable1.setDefaultEditor(Object.class, null);
        loadFromFileToTable();
    }
    
    
    private void loadFromFileToTable() {
        model.setRowCount(0);
        
        String mySupId = findSupervisorIdForStudent(tpNum);
        if (mySupId == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "can't find your supervisor, pls contect System Admin");
            return;
        }

        try (BufferedReader br = new BufferedReader(new FileReader(FILE_TS))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.trim().isEmpty()) continue;

                    String[] p = line.split(",", 4);
                    if (p.length < 4) continue;

                    TimeSlot ts = new TimeSlot( p[0].trim(), p[1].trim(), p[2].trim(), p[3].trim() );

                    if (!ts.getSupervisorId().equalsIgnoreCase(mySupId)) continue;
                    if (!"available".equalsIgnoreCase(ts.getStatus())) continue;

                    model.addRow(new Object[]{ ts.getSupervisorId(), ts.getDate(), ts.getTime(), ts.getStatus() });
                }

                if (model.getRowCount() == 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Your supervisor currently has no available time slots.");
                }
            } catch (IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "cannot read the file");
            }
    }

    private String findSupervisorIdForStudent(String tpNum) {
        try (BufferedReader br = new BufferedReader(new FileReader(FILE_AS))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] a = line.split(",", 8);
                if (a.length < 8) continue;

                String supId  = a[1].trim();
                String tpNum2   = a[3].trim();
                String status = a[7].trim();

                if (tpNum2.equalsIgnoreCase(tpNum) && status.equalsIgnoreCase("Active")) {
                    return supId;
                }
            }
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "cannot read the file");
        }
        return null;
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(model);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Reschedule");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a timeslot to reschedule", "Time slot reschedule error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int modelRow = jTable1.convertRowIndexToModel(row);

        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to reschedule to this timeslot?");
        if (option != JOptionPane.YES_OPTION) return;

        TimeSlot newSlot = new TimeSlot(
            String.valueOf(model.getValueAt(modelRow, 0)).trim(),
            String.valueOf(model.getValueAt(modelRow, 1)).trim(),
            String.valueOf(model.getValueAt(modelRow, 2)).trim(),
            "available"
        );


        Appointment newAppt = new Appointment( tpNum, newSlot.getSupervisorId(), newSlot.getDate(), newSlot.getTime(), "Pending", "-" );
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(FILE_AP, true))) {
            bw.write(String.join(",",
                    newAppt.getTpNum(),
                    newAppt.getSupervisorID(),
                    newAppt.getDate(),
                    newAppt.getTime(),
                    newAppt.getStatus(),
                    newAppt.getFeedback() ));
            bw.newLine();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error writing appointments.txt: " + e.getMessage(), "File Write Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        java.util.List<String> apptKept = new java.util.ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader(FILE_AP))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.trim().isEmpty()) continue;
                String[] p = line.split(",", 6);
                if (p.length < 6) continue;
                
                Appointment ap = new Appointment( p[0].trim(), p[1].trim(), p[2].trim(), p[3].trim(), p[4].trim(), p[5].trim() );
                
                boolean OldAppointment = ap.getTpNum().equalsIgnoreCase(this.tpNum) &&
                        ap.getSupervisorID().equalsIgnoreCase(this.supervisorID) &&
                        ap.getDate().equals(this.date) &&
                        ap.getTime().equals(this.time);
                    

                if (!OldAppointment) {
                    apptKept.add(line);
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading appointments.txt: " + e.getMessage(), "File Read Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (BufferedWriter bw = new BufferedWriter(new FileWriter(FILE_AP))) {
            for (String s : apptKept) {
                bw.write(s);
                bw.newLine();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error rewriting appointments.txt: " + e.getMessage(), "File Write Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        java.util.List<String> tsKept = new java.util.ArrayList<>();
        boolean newSlotRemoved = false;

        try (BufferedReader br = new BufferedReader(new FileReader(FILE_TS))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.trim().isEmpty()) continue;
                
                String[] t = line.split(",", 4);
                if (t.length < 3) continue;

                TimeSlot ts = new TimeSlot(t[0].trim(), t[1].trim(), t[2].trim(), t[3].trim());

                if (!newSlotRemoved 
                        && newSlot.getSupervisorId().equalsIgnoreCase(ts.getSupervisorId()) 
                        && newSlot.getDate().equals(ts.getDate())
                        && newSlot.getTime().equals(ts.getTime())) {
                        newSlotRemoved = true;
                        continue;}
                
                tsKept.add(line);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading timeslot.txt: " + e.getMessage(), "File Read Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        TimeSlot oldSlot = new TimeSlot(this.supervisorID, this.date, this.time, "available");
        boolean existsOld = false;
        for (String s : tsKept) {
            if (s.trim().equalsIgnoreCase(String.join(",", oldSlot.getSupervisorId(), oldSlot.getDate(), oldSlot.getTime(), oldSlot.getStatus()))) {
            existsOld = true;
            break;
            }
        }
        if (!existsOld) {
            tsKept.add(String.join(",", oldSlot.getSupervisorId(), oldSlot.getDate(), oldSlot.getTime(), oldSlot.getStatus()));
        }

        try (BufferedWriter bw = new BufferedWriter(new FileWriter(FILE_TS))) {
            for (String s : tsKept) {
                bw.write(s);
                bw.newLine();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error rewriting timeslot.txt: " + e.getMessage(), "File Write Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        StudentAppointments ap = new StudentAppointments(tpNum);
        ap.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
