package oopassignment;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class SystemadminPage extends javax.swing.JFrame {
    private int row = -1;
    private String idBeforeEdit;
    private DefaultTableModel model = new DefaultTableModel();
    private String[] columnName = {"System Admin ID", "System Admin Name", "System Admin Password", "System Admin Email", "Gender", "DOB", "Phone Number", "Status"};
    
    private ArrayList<SystemAdmin> systemAdminList = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SystemadminPage.class.getName());

    /**
     * Creates new form SystemadminPage
     */
    public SystemadminPage() {
        model.setColumnIdentifiers(columnName);
        initComponents();
        
        loadSystemAdminFromFile();
    }

    private void loadSystemAdminFromFile(){
        try{
            FileReader fr = new FileReader("systemAdmin.txt");
            BufferedReader br = new BufferedReader(fr);
            
            String eachLine;
            
            while((eachLine = br.readLine()) != null){
                if(eachLine.trim().isEmpty()){
                    continue;
                }
                
                String systemAdminData[] = eachLine.split(",");
                
                if (systemAdminData.length < 8){
                    continue;
                }
                
                SystemAdmin sa = new SystemAdmin(systemAdminData[0], systemAdminData[1], systemAdminData[2], systemAdminData[3], systemAdminData[4], systemAdminData[5], systemAdminData[6], systemAdminData[7]);
                systemAdminList.add(sa);
                model.addRow(systemAdminData);
            }
            
            br.close();
            fr.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "Error reading systemAdmin.txt: " + e.getMessage(), "File Read Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("System Admin Management");

        jLabel2.setText("System Admin ID:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("System Admin Name:");

        jLabel4.setText("System Admin Password:");

        jLabel5.setText("System Admin Email:");

        jLabel6.setText("Gender:");

        jLabel7.setText("DOB:");

        jLabel8.setText("Phone Number:");

        jLabel9.setText("Status:");

        jTable1.setModel(model);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Reset Password");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField2)
                                        .addComponent(jTextField3)
                                        .addComponent(jTextField4)
                                        .addComponent(jTextField6)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton3))
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validateData(String ID, String name, String password, String email, String dob, String phoneNum, String oldID){
        if(!ID.matches("SA\\d{1,6}")){
            JOptionPane.showMessageDialog(this, "System Admin ID must start with SA followed by 1-6 digits.");
            return false;
        }
        
        for (SystemAdmin sa: systemAdminList){
            if(sa.getadminID().equalsIgnoreCase(ID) && !sa.getadminID().equalsIgnoreCase(oldID)){
                JOptionPane.showMessageDialog(this, "System admin ID already exists!");
                return false;
            }
        }
        
        if(ID.isEmpty()){
            JOptionPane.showMessageDialog(this, "System admin ID cannot be empty!");
            return false;
        }
        
        if(name.isEmpty() || !name.matches("[A-za-z ]{3,30}")){
            JOptionPane.showMessageDialog(this, "Name should only contain characters and should be between 3 and 30 characters.");
            return false;
        }
        
        if(password.isEmpty() || password.length() < 6){
            JOptionPane.showMessageDialog(this, "Password cannot be empty and must contain at least 6 characters!");
            return false;
        }
        
        if(!email.endsWith("@gmail.com")){
            JOptionPane.showMessageDialog(this, "Email must end with @gmail.com");
            return false;
        }
        
        if(!phoneNum.matches("\\d{8,15}")){
            JOptionPane.showMessageDialog(this, "Phone number must have a minimum of 8 characters and a maximum of 15 characters");
            return false;
        }

        if(dob.isEmpty()){
            JOptionPane.showMessageDialog(this, "Date of birth cannot be empty");
            return false;
        }
        
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDate parsedDate = LocalDate.parse(dob, formatter);
            if (parsedDate.isAfter(LocalDate.now())) {
                JOptionPane.showMessageDialog(this, "Date of birth cannot be in the future!");
                return false;
            }
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format! Please enter in YYYY-MM-DD format (e.g. 2002-09-25).");
            return false;
        }
        
        return true;
    }
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = jTextField1.getText().trim();
        String name = jTextField2.getText().trim();
        String password = jTextField3.getText().trim();
        String email = jTextField4.getText().trim();
        String gender = (String) jComboBox1.getSelectedItem();
        String dob = jTextField6.getText().trim();
        String phoneNum = jTextField7.getText().trim();
        String status = (String) jComboBox2.getSelectedItem();
        
        if(!validateData(id, name, password, email, dob, phoneNum, "")){
            return;
        }
        
        String newRowData[] = {id, name, password, email, gender, dob, phoneNum, status};
        model.addRow(newRowData);
        systemAdminList.add(new SystemAdmin(id, name, password, email, gender, dob, phoneNum, status));
        
        try{
            FileWriter fw = new FileWriter("systemAdmin.txt", true);
            BufferedWriter bw = new BufferedWriter(fw);
            
            bw.write(id +","+ name +","+ password +","+ email +","+ gender +","+ dob +","+ phoneNum +","+ status);
            bw.newLine();
            
            bw.close();
            fw.close();
            
            FileWriter fw2 = new FileWriter("Accounts.txt", true);
            BufferedWriter bw2 = new BufferedWriter(fw2);
            
            bw2.write(id +","+ password +","+ "System Admin");
            bw2.newLine();
            
            bw2.close();
            fw2.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "Error updating systemAdmin.txt: " + e.getMessage(), "File Write Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        
        JOptionPane.showMessageDialog(this, "System Admin successfully added!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        row = jTable1.getSelectedRow();
        String id = String.valueOf(model.getValueAt(row, 0));
        String name = String.valueOf(model.getValueAt(row, 1));
        String password= String.valueOf(model.getValueAt(row, 2));
        String email = String.valueOf(model.getValueAt(row, 3));
        String gender = String.valueOf(model.getValueAt(row, 4));
        String dob = String.valueOf(model.getValueAt(row, 5));
        String phoneNum = String.valueOf(model.getValueAt(row, 6));
        String status = String.valueOf(model.getValueAt(row, 7));
        
        idBeforeEdit = id;
        
        jTextField1.setText(id);
        jTextField2.setText(name);
        jTextField3.setText(password);
        jTextField4.setText(email);
        jComboBox1.setSelectedItem(gender);
        jTextField6.setText(dob);
        jTextField7.setText(phoneNum);
        jComboBox2.setSelectedItem(status);
    }//GEN-LAST:event_jTable1MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String new_id = jTextField1.getText().trim();
        String new_name = jTextField2.getText().trim();
        String new_password = jTextField3.getText().trim();
        String new_email = jTextField4.getText().trim();
        String new_gender = (String) jComboBox1.getSelectedItem();
        String new_dob = jTextField6.getText().trim();
        String new_phoneNum = jTextField7.getText().trim();
        String new_status = (String) jComboBox2.getSelectedItem();
        
        if(!validateData(new_id, new_name, new_password, new_email, new_dob, new_phoneNum, idBeforeEdit)){
            return;
        }
        
        model.setValueAt(new_id, row, 0);
        model.setValueAt(new_name, row, 1);
        model.setValueAt(new_password, row, 2);
        model.setValueAt(new_email, row, 3);
        model.setValueAt(new_gender, row, 4);
        model.setValueAt(new_dob, row, 5);
        model.setValueAt(new_phoneNum, row, 6);
        model.setValueAt(new_status, row, 7);
        
        systemAdminList.get(row).setadminID(new_id);
        systemAdminList.get(row).setName(new_name);
        systemAdminList.get(row).setPassword(new_password);
        systemAdminList.get(row).setEmail(new_email);
        systemAdminList.get(row).setGender(new_gender);
        systemAdminList.get(row).setdob(new_dob);
        systemAdminList.get(row).setphoneNum(new_phoneNum);
        systemAdminList.get(row).setStatus(new_status);
        
        String editedID = systemAdminList.get(row).getadminID();
        String editedPassword = systemAdminList.get(row).getPassword();
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        
        try{
            FileReader fr = new FileReader("Accounts.txt");
            BufferedReader br = new BufferedReader(fr);
            
            ArrayList<String> accountList = new ArrayList<>();
            String eachLine;
            
            while((eachLine = br.readLine()) != null){
                if(eachLine.split(",")[0].equals(idBeforeEdit)){
                    accountList.add(editedID +","+ editedPassword +","+ "System Admin");
                    continue;
                }
                accountList.add(eachLine);
            }
            
            br.close();
            fr.close();
            
            FileWriter fw = new FileWriter("Accounts.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            
            for (String line : accountList){
                bw.write(line);
                bw.newLine();
            }
            
            bw.close();
            fw.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "Error updating Accounts.txt: " + e.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            FileWriter fw = new FileWriter("systemAdmin.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i=0; i<systemAdminList.size(); i++){
                String eachLine = model.getValueAt(i, 0) +","+ model.getValueAt(i, 1) +","+ model.getValueAt(i, 2) +","+ model.getValueAt(i, 3) +","+ model.getValueAt(i, 4) +","+ model.getValueAt(i, 5) +","+ model.getValueAt(i, 6) +","+ model.getValueAt(i, 7);
                bw.write(eachLine);
                bw.newLine();
            }
            
            bw.close();
            fw.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "Error updating systemAdmin.txt" + e.getMessage(), "File Write Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JOptionPane.showMessageDialog(this, "System admin successfully edited!");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
        }else{
            int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this row?");
            if(option == 0){
                String deletedID = systemAdminList.get(row).getadminID();
                model.removeRow(row);
                systemAdminList.remove(row);
                
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField6.setText("");
                jTextField7.setText("");

                try{
                    FileReader fr = new FileReader("Accounts.txt");
                    BufferedReader br = new BufferedReader(fr);
                    ArrayList<String> accountList = new ArrayList<>();
                    String eachLine;
                    
                    while((eachLine = br.readLine()) != null){
                        if(!eachLine.split(",")[0].equals(deletedID)){
                            accountList.add(eachLine);
                        }
                    }
                    
                    br.close();
                    fr.close();
                    
                    FileWriter fw = new FileWriter("Accounts.txt");
                    BufferedWriter bw = new BufferedWriter(fw);
                    
                    for (String line : accountList){
                        bw.write(line);
                        bw.newLine();
                    }
                    
                    bw.close();
                    fw.close();
                }catch(IOException e){
                    JOptionPane.showMessageDialog(this, "Error updating Accounts.txt: " + e.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                try{
                    FileWriter fw = new FileWriter("systemAdmin.txt");
                    BufferedWriter bw = new BufferedWriter(fw);
                    
                    for (SystemAdmin sa : systemAdminList){
                        bw.write(sa.getadminID() +","+ sa.getName() +","+ sa.getPassword() +","+ sa.getEmail() +","+ sa.getGender() +","+ sa.getdob() +","+ sa.getphoneNum() +","+ sa.getStatus());
                        bw.newLine();
                    }           
                    
                    bw.close();
                    fw.close();
                    
                    JOptionPane.showMessageDialog(this, "System Admin successfully deleted.");
                    jTable1.clearSelection();
                    row = -1;
                    
                }catch(IOException e){
                    JOptionPane.showMessageDialog(this, "Error updating systemAdmin.txt: " + e.getMessage(), "File Write Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Please select a row to reset password");
        }else{
            int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to reset password for this account?\nThis action will reset the password of the account to a default password and cannot be undone", "Confirm Reset Password", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            
            if (option == JOptionPane.YES_OPTION){
                String defaultPassword = "password123";
                model.setValueAt(defaultPassword, row, 2);
                systemAdminList.get(row).setPassword(defaultPassword);
                String id = systemAdminList.get(row).getadminID();
                
                try {
                    FileReader fr = new FileReader("Accounts.txt");
                    BufferedReader br = new BufferedReader(fr);
                    ArrayList<String> accountList = new ArrayList<>();
                    String eachLine;
                    
                    while((eachLine = br.readLine()) != null){
                        if(eachLine.split(",")[0].equals(id)){
                            accountList.add(id +","+ defaultPassword +","+ "System Admin");
                            continue;
                        }
                        accountList.add(eachLine);
                    }
                    
                    br.close();
                    fr.close();
                    
                    FileWriter fw = new FileWriter("Accounts.txt");
                    BufferedWriter bw = new BufferedWriter(fw);
                    
                    for (String line : accountList){
                        bw.write(line);
                        bw.newLine();
                    }
                    
                    bw.close();
                    fw.close();
                
                }catch(IOException e){
                    JOptionPane.showMessageDialog(this, "Error updating Accounts.txt: " + e.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                try{
                    FileWriter fw = new FileWriter("systemAdmin.txt");
                    BufferedWriter bw = new BufferedWriter(fw);
                    
                    for (SystemAdmin sa : systemAdminList){
                        bw.write(sa.getadminID() +","+ sa.getName() +","+ sa.getPassword() +","+ sa.getEmail() +","+ sa.getGender() +","+ sa.getdob() +","+ sa.getphoneNum() +","+ sa.getStatus());
                        bw.newLine();
                    }
                    
                    bw.close();
                    fw.close();
                    
                    JOptionPane.showMessageDialog(this, "The password of this account has been reset to the default password: " + defaultPassword, "Password reset successful", JOptionPane.INFORMATION_MESSAGE);
                    
                    jTable1.clearSelection();
                    row = -1;
                    
                }catch(IOException e){
                    JOptionPane.showMessageDialog(this, "Error updating systemAdmin.txt: " + e.getMessage(), "File Write Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        SystemAdminMainMenu menu = new SystemAdminMainMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SystemadminPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
