package oopassignment;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class SystemAdminMainMenu extends javax.swing.JFrame {
    private int row = -1;
    private DefaultTableModel model = new DefaultTableModel();
    private String[] columnName = {"Account ID", "Account Role", "Log in Attempts"};
            
    ArrayList<Accounts> accountList = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SystemAdminMainMenu.class.getName());

    /**
     * Creates new form SystemAdminMainMenu
     */
    public SystemAdminMainMenu() {
        model.setColumnIdentifiers(columnName);
        initComponents();
        
        loadAccountsFromFile();
    }
    
    private void loadAccountsFromFile(){
        try{
            FileReader fr = new FileReader("Accounts.txt");
            BufferedReader br = new BufferedReader(fr);
            
            String eachLine;
            
            while((eachLine = br.readLine()) != null){
                if(eachLine.trim().isEmpty()){
                    continue;
                }
                
                String accountDetails[] = eachLine.split(",");
                List<String> account = new ArrayList<>();
                
                
                if(accountDetails.length < 4){
                    account.add(accountDetails[0]);
                    account.add(accountDetails[2]);
                    account.add("0");
                    Accounts a = new Accounts(accountDetails[0], accountDetails[2], "0");
                    accountList.add(a);
                    model.addRow(account.toArray());
                    continue;
                }
                
                account.add(accountDetails[0]);
                account.add(accountDetails[2]);
                account.add(accountDetails[3]);
                Accounts a = new Accounts(accountDetails[0], accountDetails[2], accountDetails[3]);
                accountList.add(a);
                model.addRow(account.toArray());
            }
            
            br.close();
            fr.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "Error reading Accounts.txt" + e.getMessage(), "File Read Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void updatePasswordInFile(String fileName, String id, String password){
        try{
            FileReader fr = new FileReader(fileName);
            BufferedReader br = new BufferedReader(fr);
            ArrayList<String> updatedList = new ArrayList<>();
            String eachLine;
            
            while((eachLine = br.readLine()) != null){
                if(eachLine.trim().isEmpty()){
                    continue;
                }
                
                String parts[] = eachLine.split(",");
                if(parts[0].trim().equals(id.trim())){
                    int passwordIndex = fileName.equalsIgnoreCase("Accounts.txt") ? 1 : 2;
                    parts[passwordIndex] = password;
                    eachLine = String.join(",", parts);
                }
                updatedList.add(eachLine);
            }
            br.close();
            fr.close();
            
            FileWriter fw = new FileWriter(fileName);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for (String line : updatedList){
                bw.write(line);
                bw.newLine();
            }
            
            bw.close();
            fw.close();
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "Error updating " + fileName +" "+ e.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("System Admin Main Menu");

        jTable1.setModel(model);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Reset Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Manage Students");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Manage Supervisors");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Manage Faculty Admin");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Manage System Admin");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Log out");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(jButton2)
                        .addGap(12, 12, 12)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton6))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Please select a row to reset password");
        }else{
            int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to reset password for this account?\nThis action will reset the password of the account to a default password and cannot be undone", "Confirm Reset Password", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (option == JOptionPane.YES_OPTION){
                String defaultPassword = "password123";
                String id = accountList.get(row).getId();
                String role = accountList.get(row).getRole();
                
                updatePasswordInFile("Accounts.txt", id, defaultPassword);
                accountList.get(row).setAttempts("0");
                model.setValueAt("0", row, 2);
                
                
                if(role.equals("Student")){
                    updatePasswordInFile("students.txt", id, defaultPassword);
                } else if (role.equals("Supervisor")){
                    updatePasswordInFile("supervisor.txt", id, defaultPassword);
                } else if (role.equals("Faculty Admin")){
                    updatePasswordInFile("facultyAdmin.txt", id, defaultPassword);
                } else if (role.equals("System Admin")){
                    updatePasswordInFile("systemAdmin.txt", id, defaultPassword);
                }
                
                try{
                    FileReader fr = new FileReader("Accounts.txt");
                    BufferedReader br = new BufferedReader(fr);
                    ArrayList<String> accountList = new ArrayList<>();
                    String eachLine;
                    
                    while((eachLine = br.readLine()) != null){
                        if(eachLine.trim().isEmpty()){
                            continue;
                        }
                        String parts[] = eachLine.split(",");
                        if(parts[0].trim().equals(id.trim())){
                            if(parts.length >= 4){
                                parts[3] = "0";
                                eachLine = String.join(",", parts);
                            }else{
                                accountList.add(eachLine);
                                continue;
                            }
                        }
                        accountList.add(eachLine);
                    }
                    br.close();
                    fr.close();
                    
                    FileWriter fw = new FileWriter("Accounts.txt");
                    BufferedWriter bw = new BufferedWriter(fw);
                    
                    for (String line : accountList){
                        bw.write(line);
                        bw.newLine();
                    }
                    
                    bw.close();
                    fw.close();
                }catch(IOException e){
                    JOptionPane.showMessageDialog(this, "Error resetting attempts in Accounts.txt" + e.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                JOptionPane.showMessageDialog(this, "The password for the account " + id + " has been reset to default ('password123')");
                jTable1.clearSelection();
                row = -1;
                
                
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        row = jTable1.getSelectedRow();
        String id = String.valueOf(model.getValueAt(row, 0));
        String role = String.valueOf(model.getValueAt(row, 1));
        String attempts = String.valueOf(model.getValueAt(row, 2));

    }//GEN-LAST:event_jTable1MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        StudentPage sp = new StudentPage();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SupervisorPage sp = new SupervisorPage();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        FacultyadminPage fp = new FacultyadminPage();
        fp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        SystemadminPage sp = new SystemadminPage();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Log Out", JOptionPane.YES_NO_OPTION);
        if(option == JOptionPane.YES_OPTION){
            LoginPage2 login = new LoginPage2();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SystemAdminMainMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
